name: CI

on:
  workflow_dispatch: {}
  push:
    tags:
    - "v*.*.*"
    - "v*.*.*-rc*"
  pull_request:
    branches:
    - main
    types:
    - closed

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    if: github.event.pull_request.merged == true

    steps:
      - name: Say hi
        run: |
          echo hi
