name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
    - main

jobs:
  job1:
    outputs:
       test: ${{ steps.step1.outputs.test }}
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
      - name: Step name ${{steps.step1.outputs.test}} ${{steps.step2.outputs.test}}
        run: echo "${{steps.step1.outputs.test}} ${{steps.step2.outputs.test}}"

  job_15:
    needs: ["job1"]
    runs-on: ubuntu-latest
    if: true
    steps:
      - name: always skip
        run: echo hi

  job2:
    needs: ["job1", "job_15"]
    runs-on: ubuntu-latest
    if: ${{ !failure() && !cancelled() }}
    steps:
      - name: Use outputs ${{ needs.job1.outputs.test }}
        run: echo "hi"
