name: CI

on:
  workflow_dispatch: {}
  create:
    branches-ignore:
    - '**'
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
  pull_request:
    branches:
    - main
    types:
    - closed

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: Say hi
        run: |
          echo hi
