name: CI

on:
  workflow_dispatch: {}
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
  pull_request:
    branches:
    - main
    types:
    - closed

jobs:
  job1:
    outputs:
       test: ${{ steps.step1.outputs.test }}
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
      - name: Step name ${{steps.step1.outputs.test}} ${{steps.step2.outputs.test}}
        run: echo "${{steps.step1.outputs.test}} ${{steps.step2.outputs.test}}"
  job2:
    needs: ["job1"]
    runs-on: ubuntu-latest
    if: ${{ needs.job1.outputs.test != '' }
    steps:
      - name: Use outputs ${{ needs.job1.outputs.test }}
        run: echo "hi"
