name: CI

on:
  push:
    branches:
    - main

jobs:
  job1:
    outputs:
       test: ${{ steps.step1.outputs.test }}
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "test1=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
      - name: Step name ${{steps.step1.outputs.test}} ${{steps.step2.outputs.test}}
        run: echo "${{steps.step1.outputs.test}} ${{steps.step2.outputs.test}}"
      - name: Always fail
        run: exit 1
  job2:
    needs: ["job1"]
    runs-on: ubuntu-latest
    if: always() #${{ needs.job1.outputs.test != '' }}
    steps:
      - name: Use outputs ${{ needs.job1.outputs.test }}
        run: echo "hi"
