name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build

    steps:
      - name: Say hi
        run: |
          echo hi
